# ==============================================================
# = Discovery Service Eureka Server
# = Dash: http://localhost:8761
# ==============================================================

spring:
  application:
    name: EurekaServer

server:
  port: 8761
  tomcat:
    max-threads: 5
    
# ==============================================================
# = Eureka Parameters
# ==============================================================  
eureka:
  instance:
    hostname: localhost
    #Specifica se la registrazione avviene tramite ip
    preferIpAddress: true
# ==============================================================
# = Impostazione Server
# ==============================================================      
  server:
    #Abilita o disabilita l'auto preservazione
    enableSelfPreservation: true
    #Durata (in ms) della cache
    responseCacheUpdateIntervalMs: 60000
    #Tempo di attesa in ms di deregistrazione del servizio (def 60000)
    evictionIntervalTimerInMs: 30000
    #Tempo di attesa (in secondi) prima di accettare richieste
    waitTimeInMsWhenSyncEmpty: 5
    #Time out di connessione al peer
    peer-node-connect-timeout-ms: 500
# ==============================================================
# = Impostazione Client
# ==============================================================  
  client:
    #Un Servizio Eureka è escluso dalla registrazione in Eureka
    registerWithEureka: false
    #Non esegue la cache in locale 
    fetchRegistry: false
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://user:password@localhost:8761/eureka/} 
      
# ==============================================================
# = Parametri Sicurezza JWT 
# ==============================================================
sicurezza:
    userpwd: 'password'
    adminpwd: 'password'
